### ISSUE TITLE
[feat] Adicionar interfaces e classes básicas da Abstract Syntax Tree

### ISSUE THREAD

**Issue by talDoFlemis** [talDoFlemis/mija#13]
# **🚀 Nova Feature**

## **A sua feature é relacionada com algum problema?. Por favor descreva**

Gostaria que os parsers retornassem uma árvore sintática abstrata que possuisse o padrão de vistor.

### AST

1. [x] Adicionar o pacote `syntaxtree` ao java
2. [x] Adicionar classe abstrata Node para ser a base da AST que possu
3. [x] Adicionar classe abstrata Statement que extende Node
4. [x] Adicionar classe abstrata Expression que extende Node
5. [x] Adicionar classe abstrata Type que extende Node
6. [x] Adicionar classe abstrata ClassDeclaration que extende Node
7. [x] Adicionar classe concreta Program
8. [x] Adicionar classe concreta MainClass
9. [x] Adicionar outras classes que estao no print...
> Nao precisa adicionar construtor nem campos, só a definição da classe e a extensão dela das abstratas ja serve

### Visitors
1. [x] Adicionar pacote `visitor` ao java
2. [x] Adicionar interface AstVisitor genérica que consome todos os cabas da AST como
```java
public interface ASTVisitor<T> {
    T visit(Program p)
    T visit(MainClass m)
    // E assim para cada nós da árvore
}
```
> Essa interface genérica vai ajudar tanto na hora de um visitor que retorna `void` como os visitor que retorna verifica tipo e representacao intermediária, garantindo que a gente não duplique código e sempre todos os nós estejam aceitando esse caba

## **Contexto Adicional**

Capítulo 4 do Livro Modern Compiler Implementation in Java
![image](https://github.com/talDoFlemis/mija/assets/33133120/30c41fcb-3aa4-489a-85dd-a7787aedc9ad)

**Comment by ArtroxGabriel** [comment]
Closed by #26
